# Generated by Django 2.0 on 2018-04-20 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='task',
            new_name='description',
        ),
        migrations.AddField(
            model_name='todolist',
            name='taskName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
